dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: qdjZolfOb8enDPYQNYlRfGPEKMb/UC2Zv1GNGdIIRU8jHBNAZWWHFw9FwI1WSHvVQJ9OjVQvYMr0BCyoQZr9lb8seb1ktHg26zHTqTZItdM8ooeKVP2Z87Alv8allsyxZ8X+DRQSfvhDoaHwfsxfhoEtuWC7NoY66OVN1CqTYsxCeGhrGsCCO8NC/YbdGMSBt4YBLP5AFMAQ13s4Lo0qO5MTjKUUdUu0mik0FXPBfpEzKzZsP1G8aZuw6eAujaqzRE50Yg5ZZMFqLholukkXvVYR8s7GH+TnDx6kcG+89xmxF9mAVAXF7NFzacbKVOW8WjlmwLsDRfSc2Yjwfq7d4akqjPG6IuIUt9a3peyu6loIe1nKcHFzDO/GPSAZ9M1E09pXDDkmsi5i8bZLf9s36uEYtKGpExSIcHLW/DwQivTE6to/02ecANdhd+CJVE1ILcxvB7kdNSTNMs3kNyKd+Ke8wO08mX2DcYGn1sDp3qQkSTws45hR9aLzyGAmbPuCgI6Wmx4YGrnNSLfk7deJVRkqSXBTVBMGDjvnH3zS5iET2r+lWcVLS/rE7E7xQASVVvx5AvnmPDmBuUsL0knCzsMPWd8ROagerrspYGUa/do1eAdMwqVMVeE/p3fcV0lfJVwYMHlUaOGoT4ZyXBGwTJreMnUvYKtElMSeX/xfedc=
