dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    secure: Ku7w/CmsPq1Ub7gAx7fvGxi0Zz9cQqVnVXwFWNcoM0Iq+bArtZfeBn566ptC7vA4q0sSMVWJ/hJytR8maRoCJfqB2coXsJb3S/eN1rWlIzj9U0YulkhoIyF5z4geaniU9tJbBI3pPKA0y1yz7iPFdPnOBdEwwNrAibwxMHazsV1UEVjYlJS0hL1iDBkeyZi/lf5aXsBoJ87ILIzF4NhbB39uIGhk1ZoEJUkL4ILmqaagJ6hijdlT2i8mca9O2lFTOuSEP/WG5jf5MzACgZWbZKK53grHi1njbxN3QapVFkMXI/+MQfILkBA76OXk7KQsSJjH+P4GDBxGulXO0Mt40FE3UlJkveq+kOerg8jF6f6JHJlD64C3OKpcwm09eTzd/8KD14SrCZCzl/80nylsOKhqm5zY2chhmSIANKt56RFow9v3PhJate29XQjZxDJfb3fWjoZKxlWuCEhbaos1d9RK2u+d3eAPgeq/FVTxdCXcmdQpkFZ7KyBkXYTWJpCDGu77txWB8xG33JA8nOIX2i7h8XnahK57dS0i5d9TD7N91nmk21qyBQ4pFX58ry1Tghj5DbBT6Zs1fIJbnjjumG8/sHckmkUtuUPWxda56Xo4881XiqWyjA2PmmdToCtUbFPm4kqesZezWOWCalg4AjRaNxnUSJtxLYmoZXDiy8Q=
