dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    secure: AnLp5kwwBuRJXeM7F17iExsJeDsZ4mwJ4xYqedIkCqIFPD1b9kkqjOPNk6TG0lsO4tVt2+1LZn9zpC0HSSzf5YoZe06nWGa2WA/3kdTx1rj4Tsfn+MMa0hPXbtkQZ9yLReLgl0VSRWRiOK4BBld21L2F117K1jP5qk8Xj/QRYald2L15Fu4wiuDXLczgwAibayhTRH8ZxtLCBq1oGX5/6HtaNi9IPdM4GcpeDNp7d/SyWWqxD4ACtSNPRaKmej45iLHoUcB7RsHrlW0Jd2x1N+ZO+Mln081BvPTWzrXZadzGHf5OW37lYaCnkNRp8v6aT4n2tadYWmupWYnTJe1okI8lvGYX1KN+tC/NZv61F7+hxtwcml11mGzZjRlwBB9lqeiC+lygwwoixLLNN3oLLJBNRcnAX85t7/p7PCF7DoNKmWyJOKRfQrouF46BR7P1p5iC51X+y3ff+yMmA503CBfWdIq39WLAKP8ZBo0fLws5mu3zJ3JTthIT3S/VhSMcC1t5oViq3KWx6Vec9eKJvw8Z0EELfDd3RmDgZ9g0JXQ0hTA0PtfLdKG+9aAwhiOADnCwWRdUR3mp6Be06vVz6lekFmdf5Ey09EY4nwIIDogLolsXthJ+homAc22yobTBisQWAXHW9Mi9wwuFEzY1Q+e5R9oUcARFs5kcPlnFuEU=
